### ISSUE TITLE
Non-Integer Pixel Coordinates Causing TypeError in `tutorials_mnmst_histology.ipynb`

### ISSUE THREAD

**Issue by KaishinShaw** [xkmaxidian/MNMST#2]
### Issue Description:
In the `tutorials/tutorials_mnmst_histology.ipynb` notebook within the MNMST project, there is a step titled "Set coordinates" where `x_pixel` and `y_pixel` are adjusted using a `scale_fact`. The code snippet involved is:

```python
adata.obs["x_array"] = adata.obs["x2"]
adata.obs["y_array"] = adata.obs["x3"]
adata.obs["x_pixel"] = adata.obs["x4"] * scale_fact
adata.obs["y_pixel"] = adata.obs["x5"] * scale_fact
```

Unlike another tutorial (`SpaGCN/tutorial/tutorial.ipynb`) in the SpaGCN project, it appears that `x_pixel` and `y_pixel` are not adjusted using `scale_fact` in a consistent manner. Furthermore, since `scale_fact` may not be an integer, `x_pixel` and `y_pixel` become non-integers, leading to a `TypeError` when used as slice indices in image processing:

```python
nbs = image[
    max(0, x_pixel[i] - beta_half) : min(max_x, x_pixel[i] + beta_half + 1),
    max(0, y_pixel[i] - beta_half) : min(max_y, y_pixel[i] + beta_half + 1)
]
```

This error occurs because Python requires slice indices to be integers. If `x_pixel[i]` or `y_pixel[i]` are non-integers, even with an integer `beta_half`, the resulting indices might still be non-integers.

### Suggested Fix:
To resolve this, I suggest ensuring that all pixel values are explicitly converted to integers before being used as indices. This can be done using list comprehensions as shown below:

```python
adata.obs["x_pixel"] = [int(x) for x in adata.obs["x_pixel"]]
adata.obs["y_pixel"] = [int(y) for y in adata.obs["y_pixel"]]
```

This tweak will ensure that all pixel indices remain integers, thus preventing the `TypeError`.

### Impact:
This issue, if unresolved, can disrupt image processing tasks in automated pipelines, particularly those involving spatial coordinates in histology images. Addressing it will enhance the robustness and reliability of the tutorial scripts.

### Request:
I look forward to any feedback or alternative solutions you might suggest. Thank you for your attention to this matter!

**Comment by bbchond** [comment]
Hi, dear @KaishinShaw , I am sorry for the late reply.
The integration of morphological information was not well addressed in this paper, and we provide detailed tutorials on this in our other paper MuCST, which can be accessed at [bioRxiv](https://www.biorxiv.org/content/10.1101/2024.06.26.600708v1), where the full code for morphological information extraction can be found. I appreciate you pointing out this error, and I will update that part of the tutorials later.

**Comment by bbchond** [comment]
Hi, @KaishinShaw 
Thank you for bringing this issue to my attention. I have resolved the bug you reported. If you have any other issues or if the problem persists, please feel free to reopen this issue.

Best regards, Yu Wang
